version: 3.3


services:
  postgres:
    image: postgres:13
    enviroment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=root2
      - POSTGRES_PASSWORD=admin2039u
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgressql/dataoc
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - POSTGRES_DEFAULT_EMAIL=admin@admin.com
      - POSTGRES_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
