version: "3.8"

services:
  my_store:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/

    depends_on:
      - postgres
    command: npm run dev

  postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres234
      - POSTGRES_DB=my_store
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/docker/volumes/dbdata/_data
