version: "3.8"


services:
  my_store:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src

    depends_on:
      - postgres
    command: npx nodemon index.js

  postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root234
      - POSTGRES_DB=my_store
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/docker/volumes/dbdata/_data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres
